[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --only=production --prefix server || npm install --only=production --prefix server"]

[phases.build]
cmds = []

[start]
cmd = "npm start --prefix server"
