[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd server && npm ci --only=production || npm install --only=production"]

[phases.build]
cmds = []

[start]
cmd = "cd server && npm start"
